Repository Soumyajit2825/TO-DO-LIST, pull requests merged in 2022-10, with the labels that each got.

#5 improved todo
  to_do.css
  to_do.html
  to_do.js
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#13 Updates ReadMe and Adds All Contributors
  README.md
  contributors.json
Labels: hacktoberfest, hacktoberfest-accepted

#17 increased size
  to_do.css
Labels: hacktoberfest, hacktoberfest-accepted

#29 [BUG FIX]: Add scroll to the todo Container
  to_do.css
Labels: bug, hacktoberfest, hacktoberfest-accepted

#32 Added favicons
  favicon/about.txt
  favicon/android-chrome-192x192.png
  favicon/android-chrome-512x512.png
  favicon/apple-touch-icon.png
  favicon/favicon-16x16.png
  favicon/favicon-32x32.png
  favicon/favicon.ico
  favicon/site.webmanifest
  to_do.html
Labels: hacktoberfest, hacktoberfest-accepted

#40 Resolve background
  contributors.json
  to_do.css
Labels: bug, hacktoberfest, hacktoberfest-accepted

#47 Feature: Enter keypress to add a todo
  contributors.json
  light-dark-mode.js
  to_do.js
Labels: hacktoberfest, hacktoberfest-accepted

#50 Now texts are visible when we're in dark theme
  light-dark-mode.js
  to_do.css
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#54 Upgraded the to-do item
  light-dark-mode.js
  to_do.css
  to_do.html
  to_do.js
Labels: hacktoberfest, hacktoberfest-accepted

#62 Changed the font size and border
  to_do.css
Labels: hacktoberfest, hacktoberfest-accepted

#63 Updated Readme.md
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#66 feat(count-indicator): add todo and completed count in TODO and COMPL…
  to_do.js
Labels: hacktoberfest, hacktoberfest-accepted

#67 fix(fav-icon): fix fav icon link and remove un-necessary files
  favicon/android-chrome-192x192.png
  favicon/android-chrome-512x512.png
  favicon/apple-touch-icon.png
  favicon/favicon-16x16.png
  favicon/favicon-32x32.png
  to_do.html
Labels: hacktoberfest, hacktoberfest-accepted
