Repository Soumyajit2825/TO-DO-LIST, pull requests merged in 2024-01, with the labels that each got.

#79 Reversed the order in which list items are displayed
  contributors.json
  index.html
  to_do.css
  to_do.js
Labels: apertre, easy

#88 solved the issue #74 and changed the waves pattern
  aos/aos.css
  aos/aos.js
  contributors.json
  index.html
  to_do.css
Labels: apertre, medium

#83 Changed Layout, Added Deadline Feature
  contributors.json
  index.html
  to_do.css
  to_do.js
Labels: apertre, medium

#98 update the README.md file
  README.md
  contributors.json
  dark-mode.png
  light-mode.png
Labels: apertre, easy

#105 mobile responsiveness update
  contributors.json
  index.html
  to_do.css
Labels: apertre, easy

#109 darkMode
  index.html
  light-dark-mode.js
  to_do.css
Labels: apertre, easy

#111 feat:add_issue_template_sucessfully
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
Labels: documentation, apertre, easy

#114 UPDATE README.md File
  README.md
  Readme_logo.png
Labels: apertre, easy

#115 Add reward features upon completion of work
  index.html
  tick.png
  to_do.css
  to_do.js
Labels: apertre, medium
